"""Small dependency-free HTML report generator."""

from __future__ import annotations

from html import escape
from collections.abc import Iterable

from .models import Finding


def render_html(findings: Iterable[Finding], *, title: str = "NetDefender Security Report") -> str:
    items = list(findings)
    cards = []
    for finding in items:
        evidence = "<ul>" + "".join(
            f"<li><strong>{escape(str(key))}:</strong> {escape(str(value))}</li>"
            for key, value in finding.evidence.items()
        ) + "</ul>"
        cards.append(
            "<article>"
            f"<h2>{escape(finding.title)}</h2>"
            f"<p><strong>Rule:</strong> {escape(finding.rule_id)} &nbsp; "
            f"<strong>Severity:</strong> {escape(finding.severity)}</p>"
            f"<p><strong>Source:</strong> {escape(finding.source_ip)} &rarr; "
            f"<strong>Target:</strong> {escape(finding.destination_ip)}</p>"
            f"{evidence}</article>"
        )
    body = "<p>No findings were generated for the supplied evidence.</p>" if not cards else "".join(cards)
    return f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8"><title>{escape(title)}</title>
<style>body{{font-family:system-ui,sans-serif;max-width:960px;margin:40px auto;padding:0 20px;background:#f6f7f9;color:#20242a}}article{{background:white;border:1px solid #ddd;border-radius:10px;padding:20px;margin:16px 0}}code{{font-family:monospace}}</style>
</head><body><h1>{escape(title)}</h1><p>Generated by NetDefender from controlled lab evidence.</p>{body}</body></html>"""
